version: '3.8'


include:
  - path:
    - ../DOCKERCOMPONENT/docker-compose-net.yml
    - ../DOCKERCOMPONENT/docker-compose-volume.yml
    env_file: .env

services:


  mysql-apione:
    container_name: mysql-apione
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=apione
      - MYSQL_DATABASE=apione
      - MYSQL_USER=apione
      - MYSQL_PASSWORD=apione
    volumes:
      - ./mysql_data_jwtrole:/var/lib/mysql
    networks:
      - laravel-apione

  apione:
    build:
      dockerfile:  ${PROJECTDIR}${CONTEINERS}/apiOne/Dockerfile
    container_name: apiOne
    volumes:
      - ${PROJECTDIR}${CONTEINERS}/apiOne/apiOne:/var/www/html
      - ${PROJECTDIR}${CONTEINERS}/apiOne/apache-config.conf:/etc/apache2/sites-available/000-default.conf
      - ${PROJECTDIR}${CONTEINERS}/apiOne/ports.conf:/etc/apache2/ports.conf
    ports:
      - "8082:82"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql-apione
    networks:
      - laravel-apione

  phpmyadminapione:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST:  mysql-apione
    depends_on:
      - mysql-apione
    ports:
      - "8037:80"
    networks:
      - laravel-apione
      # openvpn:
      #   ipv4_address: 192.168.192.6